services:
  - type: web
    name: library-games-store-backend
    env: node
    buildCommand: cd Server && npm install
    startCommand: cd Server && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
      - key: FRONTEND_URL
        value: https://your-frontend-app.vercel.app
    healthCheckPath: /health